---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: todo-app
  labels:
    app: todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-todoapp
    spec:
      containers:
        - name: todo
          image: saireddysatishkumar/todo-app:26
          ports:
            - containerPort: 8000
